title: Stichting OpenTaal
email: info@opentaal.org
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://opentaal.org"
twitter_username: OpenTaal
facebook_username: opentaal
linkedin_username: stichting-opentaal
github_username:  OpenTaal

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - LICENSE
  - README
  - generate.sh
  - deploy.sh
